#!/bin/bash
# description: Tomcat service
# processname: java
# chkconfig: - 99 1
# Source function library.
. /etc/init.d/functions



export TOMCAT_USER=tomcat
export HOME=$(cat /etc/passwd | grep $TOMCAT_USER | awk -F ':' '{print $6}')
. $HOME/.bash_profile
 
[ -d "$CATALINA_HOME" ] || { echo "Tomcat requires $CATALINA_HOME."; exit 1; }
 
case $1 in
 
  start|stop|run) 
    if su $TOMCAT_USER bash -c "$CATALINA_HOME/bin/catalina.sh $1"; then
      echo -n "Tomcat $1 successful"
      [ $1 == "stop" ] && rm -f $CATALINA_PID
    else
      echo -n "Error in Tomcat $1: $?"
    fi
    ;;
 
  restart)
    $0 start
    $0 stop
    ;;
 
  status)
    if [ -f "$CATALINA_PID" ]; then
      read kpid < "$CATALINA_PID"
      if ps --pid $kpid 2>&1 1>/dev/null; then
        echo "$0 is already running at ${kpid}"
      else
        echo "$CATALINA_PID found, but $kpid is not running"
      fi
      unset kpid
    else
      echo "$0 is stopped"
    fi
    ;;
 
esac   
exit 0
